sudo: required
services:
  - docker

before_install:
  - docker build -t izolotarev/docker-react -f Dockerfile.dev .

# -e CI=true
script:
  - docker run -e CI=true izolotarev/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-009214066895"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
