sudo: required
services:
  - docker

before_install:
  - docker build -t izolotarev/docker-react -f Dockerfile.dev .

# -e CI=true
script:
  - docker run -e CI=true izolotarev/docker-react npm run test -- --coverage
